generatorName: java
library: retrofit2
inputSpec: api/openapi.yaml
groupId: dev.langchain4j
artifactId: langchain4j-langsmith
artifactVersion: 1.0.0-SNAPSHOT
artifactUrl: https://github.com/bsorrentino/langsmith4j-sdk
artifactDescription: Langsmith integration for Langchain4j.

# SCM connection in generated pom.xml (Default: scm:git:git@github.com:openapitools/openapi-generator.git)
scmConnection: scm:git:git@github.com/bsorrentino/langsmith4j-sdk.git

scmDeveloperConnection: scm:git:git@github.com/bsorrentino/langsmith4j-sdk.git
# SCM developer connection in generated pom.xml (Default: scm:git:git@github.com:openapitools/openapi-generator.git)

scmUrl: https://github.com/bsorrentino/langsmith4j-sdk.git
# SCM URL in generated pom.xml (Default: https://github.com/openapitools/openapi-generator)

# The name of the license (Default: Unlicense)
licenseName: MIT

# The URL of the license (Default: http://unlicense.org)
licenseUrl: https://opensource.org/license/mit

developerEmail: bartolomeo.sorrentino@gmail.com
#developer email in generated pom.xml (Default: team@openapitools.org)

developerName: bsorrentino
#developer name in generated pom.xml (Default: OpenAPI-Generator Contributors)

developerOrganization:
#developer organization in generated pom.xml (Default: OpenAPITools.org)
  
developerOrganizationUrl:
#developer organization URL in generated pom.xml (Default: http://openapitools.org)

# Select the complementary documentation annotation library. (Default: none)
#     none - Do not annotate Model and Api with complementary annotations.
#     swagger1 - Annotate Model and Api using the Swagger Annotations 1.x library.
#     swagger2 - Annotate Model and Api using the Swagger Annotations 2.x library.
annotationLibrary: none

apiPackage: dev.langchain4j.langsmith.api
modelPackage: dev.langchain4j.langsmith.model

# Option. Date library to use (Default: java8)
#     joda - Joda (for legacy app only)
#     legacy - Legacy java.util.Date
#     java8-localdatetime - Java 8 using LocalDateTime (for legacy app only)
#     java8 - Java 8 native JSR310 (preferred for jdk 1.8+)
dateLibrary: java8

# Enable OpenAPI Jackson Nullable library (Default: true)
openApiNullable: false

# If true, async handlers will be used, instead of the sync version (Default: false)
# asyncNative: true
